---
title: "A1_alpha_diversity"
output: html_document
date: "2025-11-11"
---

```{r Load data and libraries}
library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)

# Load object
ps = readRDS('../../datasets/ps_taxonomy.rds')

# Rarefy to chosen sequencing depth
psrare = ps %>% 
  rarefy_even_depth(sample.size = 7541, rngseed = 421)

psrare_control = subset_samples(psrare, disease == "Control")

table(sample_sums(psrare_control))

```

```{r Alpha Diversity Using Shannon, Observed}
# Calculate Shannon index, Observed alpha diversity
set.seed(421)
p = plot_richness(psrare_control, x = 'LI_status', 
                  measures = c('Shannon', 'Observed'),
                  color = 'LI_status')
p

# Generate an appropriate publication-ready plot
pdata = p$data
str(pdata)

p_formatted = pdata %>% ggplot(aes(LI_status,value,fill = LI_status)) +
  geom_boxplot(outlier.shape = NA) + 
  # geom_jitter(height=0,width=0.3) + # remove the points due to the difference in sample size
  theme_classic(base_size=12) +
  facet_wrap(~variable,ncol=2,scales = 'free_y') +
  ylab('Alpha Diversity') + 
  xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45,vjust=1,hjust=1)) +
  labs(fill='LI Status')
p_formatted

# Add a Wilcoxon test directly to the plot using stat_compare_means().
comparisons = list(c('LI','No_LI'))

p_formatted_new = p_formatted +
  stat_compare_means(comparisons = comparisons, method='wilcox.test', size=6) +
  scale_y_continuous(expand = expansion(mult = c(0.05, .1)))
p_formatted_new

# Saving plot
# ggsave('../outputs/Aim 1 - Alpha Diversity (Shannon,Observed).jpeg', plot = p_formatted_new, height=5,width=7)

```

```{r Faith PD}
library(picante)

# Calculate Faith PD
phylo_dist <- pd(t(otu_table(psrare_control)), phy_tree(psrare_control), include.root = FALSE)

# Add PD to metadata table 
sample_data(psrare_control)$PD <- phylo_dist$PD

# Plot Faith PD
faith_pd_plot <- ggplot(sample_data(psrare_control), aes(LI_status, PD,fill = LI_status)) +
  geom_boxplot(outlier.shape = NA) + 
  theme_classic(base_size=12) +
  labs(title = "Faith's Phylogenetic Diversity") +
  ylab('Faith PD') + 
  xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45,vjust=1,hjust=1))+
  labs(fill='LI Status')
faith_pd_plot

# Add a Wilcoxon test directly to the plot using stat_compare_means().
comparisons = list(c('LI','No_LI'))

p_formatted_faith = faith_pd_plot +
  stat_compare_means(comparisons = comparisons, method='wilcox.test', size=6) +
  scale_y_continuous(expand = expansion(mult = c(0.05, .1)))
p_formatted_faith

# ggsave('../outputs/Aim 1 - Alpha Diversity (FaithPD).jpeg', plot = p_formatted_faith, height=5,width=7)

```
