---
title: "A1_alpha_diversity"
output: html_document
date: "2025-11-11"
---

```{r Load data and libraries}
library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)

# Load object
ps = readRDS('../datasets/ps_taxonomy.rds')

# Rarefy to chosen sequencing depth
psrare = ps %>% 
  rarefy_even_depth(sample.size = 7541, rngseed = 421)

psrare_control = subset_samples(psrare, disease == "Control")

table(sample_sums(psrare_control))

```

```{r Alpha Diversity}
# Calculate Shannon index alpha diversity
set.seed(421)
p = plot_richness(psrare_control, x = 'LI_status', 
                  measures = c('Shannon'),
                  color = 'LI_status')
p

# Generate an appropriate publication-ready plot
pdata = p$data
str(pdata)

p_formatted = pdata %>% ggplot(aes(LI_status,value,fill = LI_status)) +
  geom_boxplot(outlier.shape = NA) + 
  # geom_jitter(height=0,width=0.3) + # remove the points due to the difference in sample size
  theme_classic(base_size=12) +
  facet_wrap(~variable,ncol=2,scales = 'free_y') +
  ylab('Alpha Diversity') + 
  xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45,vjust=1,hjust=1)) +
  labs(fill='LI Status')
p_formatted

# Add a Wilcoxon test directly to the plot using stat_compare_means().
comparisons = list( c('LI','No_LI'))

p_formatted_new = p_formatted +
  stat_compare_means(comparisons = comparisons, method='wilcox.test', size=6) +
  scale_y_continuous(expand = expansion(mult = c(0.05, .1)))
p_formatted_new

# Saving plot
ggsave('Aim 1 - Alpha Diversity.jpeg', plot = p_formatted_new, height=5,width=7)

```
